AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ember bolt

Resources:

  Bolt:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.movealong.bolt.Bolt
      CodeUri: ./target/ember-bolt-1.0-SNAPSHOT-bundle.jar
      Runtime: java8
      Role: arn:aws:iam::358324145076:role/vpc-lambda
      VpcConfig:
        SecurityGroupIds:
        - 'sg-5217f625'
        - 'sg-cb21feb3'
        SubnetIds:
        - 'subnet-6f6f1627'
        - 'subnet-27796b42'
      Environment:
        Variables:
          REDIS_SERVER: ember-lightning-0.u0uk5q.0001.use1.cache.amazonaws.com
          APP_NAME: movealong-main
      Events:
        Index:
          Type: Api
          Properties:
            Path: /
            Method: get
